### ISSUE TITLE
Not working with ionic 5

### ISSUE THREAD

**Issue by bphkns** [triniwiz/capacitor-datepicker#11]
![image](https://user-images.githubusercontent.com/17137703/80539374-04c7ff80-89c5-11ea-9d9d-9f00820d4a5a.png)
Throwing these error while compiling in android studio

**Comment by bot101** [comment]
I am having this exact same issue.

**Comment by jahanvi-droid** [comment]
Does anyone find any solution for this? Getting the same problem.
